### ISSUE TITLE
How to calculate the value (in cubic angstrom) of the accessible volume?

### ISSUE THREAD

**Issue by Jiaxing2018** [Fluorescence-Tools/avtraj#8]
Hi, I used avtraj to calculate the accessible volumes. The output files contain the number of points and the coordinates of each point, which can be visualized in pymol. I am wondering if we can get the exact value of the accessible volume in cubic angstrom or if we can just use the number of points to indicate the accessible volumes. Another question is, what does the parameter "simulation_grid_resolution" mean? If I use a lower resolution value, the number of points will be bigger. Thank you so much for your help! The program is very useful!

**Comment by tpeulen** [comment]
You are right, the volume corresponds to the number of points in an accessible volume. The conversion factor will depend on  the grid size you specified. The parameter 'simulation_grid_resolution' is the size of the voxels.
